services: 
  call_service:
    container_name: call_service
    build: ./call_service
    ports: 
      - "3000:3000"
    networks:
      - app_network
  
networks:
  app_network:
    driver: bridge
  