FROM --platform=linux/amd64 node:18-bullseye-slim as builder

WORKDIR /build
COPY package.json ./
COPY package-lock.json ./
ARG NPM_TOKEN
ENV NPM_TOKEN $NPM_TOKEN
RUN npm ci --ignore-scripts

FROM --platform=linux/amd64 node:18-bullseye-slim
RUN apt-get update && apt-get install -y dumb-init
ENV HOME=/home/app
ENV APP_HOME=$HOME/node/
ENV NODE_ENV=development
WORKDIR $APP_HOME

RUN apt-get update && \
    apt-get install -y ffmpeg unzip build-essential python3 wget &&\
    rm -rf /var/lib/apt/lists/*


RUN mkdir -p models && \
    cd models && \
    wget https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip && \
    unzip vosk-model-small-en-us-0.15.zip && \
    rm vosk-model-small-en-us-0.15.zip

# vosk-model-en-us-0.22.zip
COPY --chown=node:node . $APP_HOME
COPY --chown=node:node --from=builder /build $APP_HOME

USER node
EXPOSE 3000
EXPOSE 9320
ENTRYPOINT ["dumb-init"]
CMD ["npm", "run", "dev"]